version: '3'

volumes:
  db:

networks:
  dbbridge:
    driver: bridge
  endsbridge:
    driver: bridge

services:

  go-frontend:
    container_name: go-frontend
    build:
      context: ./frontend/
    depends_on:
      - redis-db
      - go-backend
    environment:
      - BACKEND_DNS=go-backend
    ports:
      - "8080:8080"
    networks:
      - endsbridge

  go-backend:
    container_name: go-backend
    build:
      context: ./backend/
    depends_on:
      - redis-db
    environment:
      - REDIS_DNS=redis-db
    networks:
      - dbbridge
      - endsbridge

  redis-db:
    container_name: redis-db
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - "db:/data"
    networks:
      - dbbridge
