version: '3'

volumes:
  db:

networks:
  dbbridge:
    driver: bridge

services:

  go-frontend:
    container_name: go-frontend
    build:
      context: .
      dockerfile: ../frontend/dockerfile_go-frontend
    depends_on:
      - redis-db

  redis-db:
    container_name: redis-db
    # TODO configure mysql
    build:
      context: .
      dockerfile: ../backend/dockerfile_go-backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - "db:/data"
    networks:
      - dbbridge
