apiVersion: apps/v1
kind: Deployment
metadata:
  name: production
spec:
  selector:
    matchLabels:
      name: production
  replicas: 1
  template:
    metadata:
      labels:
        name: production
    spec:
      containers:
      - name: go-backend
        image: zheraan/bruh # TODO change to go fetch the image from dockerhub
        imagePullPolicy: Always
        ports:
        - containerPort: [6379, 9000]
        env:
        - name: REDIS_DNS
          value: "redis-db"
